[package]
name = "Discord_Bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.2"
tokio = { version = "1.38.0", features = ["full"] }

[dependencies.mongodb]
version = "2.8.0"
features = ["tokio-runtime"]